pub const POLYNOMIAL_MAX_COEFFICIENTS_U8: u8 = u8::MAX;
pub const POLYNOMIAL_MAX_DEGREE_U8: u8 = POLYNOMIAL_MAX_COEFFICIENTS_U8 - 1;

pub const POLYNOMIAL_MAX_COEFFICIENTS: usize = POLYNOMIAL_MAX_COEFFICIENTS_U8 as usize;
pub const POLYNOMIAL_MAX_DEGREE: usize = POLYNOMIAL_MAX_DEGREE_U8 as usize;
